name       : apparmor
version    : 2.11.0
release    : 2
source     :
    - https://launchpad.net/apparmor/2.11/2.11/+download/apparmor-2.11.0.tar.gz : b1c489ea11e7771b8e6b181532cafbf9ebe6603e3cb00e2558f21b7a5bdd739a
license    :
    - GPL-2.0
    - LGPL-2.1
component  : security.library
summary    : AppArmor LSM user-space component
description: |
    AppArmor LSM user-space component
builddeps  :
    - pyflakes
    - python-setuptools
    - perl-gettext
setup      : |
    pushd ./libraries/libapparmor
    %autogen
build      : |
    %make -C ./libraries/libapparmor
    %make -C utils
    %make -C binutils
    %make -C parser
    %make -C profiles
install    : |
    %make_install -C ./libraries/libapparmor
    # TODO: Validate profiles, tools, etc, and make stateless!
    %make_install -C utils
    %make_install -C binutils
    %make_install -C parser
    %make_install -C profiles

    # For now remove unvalidated profiles..
    rm -v $installdir/etc/apparmor.d/*.*.*

    # systemd, inspired/helped/borrowed from Arch
    install -D -m 00755 $pkgfiles/apparmor_up.sh $installdir/usr/sbin/apparmor_up.sh
    install -D -m 00755 $pkgfiles/apparmor_down.sh $installdir/usr/sbin/apparmor_down.sh
    install -D -m 00644 $pkgfiles/apparmor.service $installdir/%libdir%/systemd/system/apparmor.service

    # Pre-enable service for Solus users
    install -D -d -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants 
    ln -sv ../apparmor.service $installdir/%libdir%/systemd/system/multi-user.target.wants/apparmor.service
