name       : apparmor
version    : 2.13.6
release    : 10
source     :
    - https://launchpad.net/apparmor/2.13/2.13.6/+download/apparmor-2.13.6.tar.gz : 4426b8b73f368889aea69cbc224ae666d4145b9520a2866cc2a915908e87ba8f
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : security.library
summary    : AppArmor LSM user-space component
description: |
    AppArmor LSM user-space component
builddeps  :
    - pkgconfig(python3)
    - dejagnu      # Tests
    - perl-gettext # Tests
    - pyflakes     # Tests
    - swig
rundeps    :
    - python3
networking : yes
environment: |
    export PYTHON=/usr/bin/python3
    export PYTHON_VERSIONS=python3
setup      : |
    cd libraries/libapparmor
    %autogen --with-python
build      : |
    %make -C libraries/libapparmor
    %make -C binutils
    %make -C parser
    %make -C profiles
    %make -C utils
install    : |
    # TODO: Validate profiles, tools, etc, and make stateless!
    %make_install -C libraries/libapparmor
    %make_install -C binutils
    %make_install -C parser
    %make_install -C profiles
    %make_install -C utils

    install -Dm 00644 $pkgfiles/apparmor.tmpfiles $installdir/usr/lib/tmpfiles.d/apparmor.conf

    # For now remove unvalidated profiles..
    rm -v $installdir/etc/apparmor.d/*.*.*
check      : |
    %make check -C libraries/libapparmor
    %make check -C binutils
    %make check -C parser
    %make check-parser -C profiles

    # This one fails because:
    # "This test is likely running on an newer kernel and will require
    # updating the list of network domain keywords"
    rm $workdir/utils/test/test-network.py
    %make -C utils check PYFLAKES=/usr/bin/pyflakes3
